server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: ronaldo
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
  output:
    ansi:
      enabled: Always # Habilita cores ANSI no console sempre

logging:
  level:
    com.ead: TRACE # Logs mais detalhados para seu pacote específico
    root:  # Nível padrão para todos os logs não especificados
    org.springframework.web: DEBUG # Logs detalhados das requisições web
    org.hibernate: INFO  # Logs padrão do Hibernate
